# Generated by Django 3.0.6 on 2020-07-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='outstanding_amount_record',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
