# Generated by Django 3.0.6 on 2020-07-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20200718_1823'),
        ('Transactions', '0002_transaction_outstanding_amount_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounts.Account'),
        ),
    ]
