# Generated by Django 3.0.6 on 2020-07-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_auto_20200718_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='outstanding_amount_record',
            field=models.FloatField(null=True),
        ),
    ]
