# Generated by Django 3.0.6 on 2020-07-22 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0004_auto_20200718_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_note',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
