# Generated by Django 3.0.6 on 2020-07-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20200722_1448'),
        ('Transactions', '0006_auto_20200722_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Account'),
        ),
    ]
