# Generated by Django 3.0.6 on 2020-07-13 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('loan_account_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('outstanding_amount', models.FloatField()),
                ('open_date', models.DateField(db_index=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('current_Status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], db_index=True, default='A', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.Customer')),
            ],
        ),
    ]
