# Generated by Django 3.0.6 on 2020-07-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20200716_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='outstanding_amount',
            field=models.FloatField(blank=True, default=models.FloatField(default=0), null=True),
        ),
    ]
