# Generated by Django 3.0.6 on 2020-07-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20200716_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='outstanding_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
