# Generated by Django 3.0.6 on 2020-07-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20200718_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='amount_credited_to_customer',
            field=models.FloatField(default=0),
        ),
    ]
