# Generated by Django 3.0.6 on 2020-07-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_address_city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_address_line_1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_address_line_2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
