# Generated by Django 3.0.6 on 2020-07-16 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_auto_20200716_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_phone',
            new_name='customer_phone_number',
        ),
    ]
